### PR TITLE
Use a thread local StringBuilder to avoid creating garbage

### PR DESCRIPTION
**Pull request by tobiasstadler**

### CODE REVIEW

**Comment by tobiasstadler** [comment]
Can anyone please have a look at this?

**Comment by felixbarny** [comment]
Sorry, I thought I had answered already. I'm not sure this makes a lot of difference. There are still allocations when calling `builder.toString()` at the end of the method.

**Comment by tobiasstadler** [comment]
Yes, there we are still allocating "garbage", but not as much as before.

**Comment by felixbarny** [comment]
The thing is that caching that StringBuilder thread-locally does add memory overhead to each thread that performs logging. By using Logback, you basically have already agreed to use a logging library that does create garbage. If you want a zero-garbage alternative, why not use log4j2? This hybrid approach might just combine the downsides of both - higher memory footprint and still creating garbage.
What's the background of this change? Did you make measurements about how this change would affect your GC counts and times?

**Comment by tobiasstadler** [comment]
Sorry for the long delay.

I want to use it in Wildfly/JBoss EAP. I did not do any performance testing, but I don't think my change will negatively affect my use case.

**Comment by eyalkoren** [comment]
@tobiasstadler can we close this one?

**Comment by tobiasstadler** [comment]
yes

**Comment by eyalkoren** [comment]
Thanks 🙏

**Pull request closed without merging**
