### PR TITLE
Fix for issue #92 : when trying to serialize null, serialize it as th…

### PR DESCRIPTION
**Pull request by nhurion**
…e string "null"

When trying to serialize a CharSequence that is null, serialize it as the string null.
To avoid null checks propagation.

### CODE REVIEW

**Comment by nhurion** [comment]
I tried to sign the CLA multiple times, always having session timeout.

**Comment by felixbarny** [comment]
Thanks for the PR ❤️ 

Could you add a test case for using a null value in `co.elastic.logging.EcsJsonSerializer#serializeFormattedMessage`?

Hm, maybe try to sign the CLA again tomorrow.

**Comment by nhurion** [comment]
I added a unit test, and actually fixed the issue now.
For the CLA I downloaded the signed document so I assume it is in order now.

**Comment by nhurion** [comment]
Tried CLA again, dunno what more I can do.

**Comment by nhurion** [comment]
Is there any way to make this thing move forward? This bug is really problematic as it prevent normal error flow.

**Comment by nhurion** [comment]
I think the CLA passed this time

**Comment by nhurion** [comment]
I don't know what else to do to make this check pass. Anyone can help?

**Comment by felixbarny** [comment]
Hey, I just returned from PTO.

I've let the CLA check run again but it seems like it did not work.

Please make sure you're using the email address that's used in git (https://patch-diff.githubusercontent.com/raw/elastic/ecs-logging-java/pull/93.patch) and that this email is also associated with your GitHub account (https://github.com/settings/emails).

**Comment by nhurion** [comment]
I associated the email and signed with that email. Hopefully this one will work.

**Comment by felixbarny** [comment]
It did work! 🎉

**Comment by felixbarny** [comment]
Thank you for your contribution!

I've released a new version: https://github.com/elastic/ecs-logging-java/releases/tag/v0.5.2

**Pull request merged**
