### PR TITLE
Adding service version

### PR DESCRIPTION
**Pull request by szisiu**
Added ECS `service.version` field support.

Refs: https://github.com/elastic/ecs-logging-java/issues/129

### CODE REVIEW

**Comment by eyalkoren** [comment]
@szisiu Thanks for your input and proposed PR!

We try to be very selective on what we choose as a primary ecs-logging configuration, and so far we did not identify `service.version` as such. The rationale is that any field for which we don't expose a dedicated config can be set through the `additionalField` config (or `KeyValuePair` in log4j2). 

Did you try that? Any reason this won't be good enough for this purpose?

**Comment by szisiu** [comment]
> @szisiu Thanks for your input and proposed PR!
> 
> We try to be very selective on what we choose as a primary ecs-logging configuration, and so far we did not identify `service.version` as such. The rationale is that any field for which we don't expose a dedicated config can be set through the `additionalField` config (or `KeyValuePair` in log4j2).
> 
> Did you try that? Any reason this won't be good enough for this purpose?

Hi, @eyalkoren. I thought that it could be a good and convenient addition. I tried and still using now the `additionalFields`. It works too. 

The final decision is yours, guys.

**Comment by tobiasstadler** [comment]
@eyalkoren Now that the Java agent integrated elastic/apm-agent-java#1726, elastic/apm-agent-java#1922 and elastic/apm-agent-java#2434 I think it makes sense to expose `service.version` as dedicated field. The agent can then automatically set the (auto discovered or explicitly set) `service.version` when using ECS reformatting or instrumenting the library (see elastic/apm-agent-java#1626).

**Comment by eyalkoren** [comment]
@tobiasstadler I agree!
Do you have the capacity to bring this to be ready for review?
If not, we can prioritize this when we get the chance.

**Comment by tobiasstadler** [comment]
I will have a look.

**Comment by felixbarny** [comment]
@szisiu Could please sign the CLA? See https://github.com/elastic/ecs-logging-java/pull/132#issuecomment-860194104. Unfortunately, we can't move forward with this PR, otherwise.

**Comment by szisiu** [comment]
> @szisiu Could please sign the CLA? See [#132 (comment)](https://github.com/elastic/ecs-logging-java/pull/132#issuecomment-860194104). Unfortunately, we can't move forward with this PR, otherwise.

Hi @felixbarny, it will be hard at this moment.

What about pushing the code provided by @tobiasstadler in https://github.com/elastic/ecs-logging-java/pull/168?

**Comment by felixbarny** [comment]
Closing in favor of https://github.com/elastic/ecs-logging-java/pull/168

**Pull request closed without merging**
