### PR TITLE
Add ECS console appender for spring boot

### PR DESCRIPTION
**Pull request by ipalbeniz**
This PR adds a console appender for spring boot (https://github.com/elastic/ecs-logging-java/issues/137)

### CODE REVIEW

**Review by eyalkoren — APPROVED** [review]
Thanks!! 
Please just confirm that you tested that this exact file works as expected when imported.

**Comment by eyalkoren** [comment]
You can also add it to the xml example in https://github.com/elastic/ecs-logging-java/blob/master/docs/tab-widgets/ecs-encoder.asciidoc

**Comment by eyalkoren** [comment]
run elasticsearch-ci/docs

**Comment by eyalkoren** [comment]
@ipalbeniz once you confirm that you manually tested that this works as expected when taken as is from the repo, I can go ahead and merge.

**Comment by ipalbeniz** [comment]
@eyalkoren I just tested it and works as expected.

**Pull request merged**
